### Data Platforms with Bruin

In [4]:
import duckdb
import pandas as pd

**Note:** Jupyter kernel is running inside of the following directory, not the notebook's directory:

`zoomcamp/data-engineering-zoomcamp/04-analytics-engineering/taxi_rides_ny`

In [13]:
# Connect to the db.
con = duckdb.connect("taxi_rides_ny.duckdb")

In [14]:
# Check all schemata.
con.execute("SELECT * FROM information_schema.schemata").df()

,catalog_name,schema_name,schema_owner,default_character_set_catalog,default_character_set_schema,default_character_set_name,sql_path
0,system,information_schema,duckdb,None,None,None,None
1,system,main,duckdb,None,None,None,None
2,system,pg_catalog,duckdb,None,None,None,None
3,taxi_rides_ny,dev,duckdb,None,None,None,None
4,taxi_rides_ny,ingestion,duckdb,None,None,None,None
5,taxi_rides_ny,main,duckdb,None,None,None,None
6,taxi_rides_ny,prod,duckdb,None,None,None,None
7,taxi_rides_ny,reports,duckdb,None,None,None,None
8,taxi_rides_ny,staging,duckdb,None,None,None,None
9,temp,main,duckdb,None,None,None,None

In [15]:
con.sql("SELECT * FROM staging.trips LIMIT 5").df()

,vendor_id,rate_code_id,pickup_location_id,dropoff_location_id,pickup_datetime,dropoff_datetime,store_and_fwd_flag,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,payment_type,payment_type_description,service_type,extracted_at
0,2.0,1.0,141,74,2021-01-16 13:51:47,2021-01-16 13:59:31,N,1.0,2.21,8.5,0.0,0.5,2.36,0.0,0.3,14.16,1.0,credit_card,yellow,2026-02-22 13:52:27.086451-05:00
1,2.0,1.0,143,143,2021-01-16 13:06:50,2021-01-16 13:09:37,N,4.0,0.70,4.5,0.0,0.5,1.56,0.0,0.3,9.36,1.0,credit_card,yellow,2026-02-22 13:52:27.086451-05:00
2,2.0,1.0,239,50,2021-01-16 13:33:32,2021-01-16 13:44:41,N,3.0,1.72,9.5,0.0,0.5,1.50,0.0,0.3,14.30,1.0,credit_card,yellow,2026-02-22 13:52:27.086451-05:00
3,2.0,1.0,48,233,2021-01-16 13:52:40,2021-01-16 14:01:10,N,3.0,1.41,7.5,0.0,0.5,2.70,0.0,0.3,13.50,1.0,credit_card,yellow,2026-02-22 13:52:27.086451-05:00
4,1.0,1.0,262,141,2021-01-16 13:07:40,2021-01-16 13:14:55,N,1.0,1.50,7.5,2.5,0.5,0.00,0.0,0.3,10.80,2.0,cash,yellow,2026-02-22 13:52:27.086451-05:00

In [17]:
con.sql("SELECT * FROM reports.trips_report").df()

,service_type,pickup_date,total_trips,total_amount,total_fare,total_tips,avg_trip_distance,avg_passenger_count
0,yellow,2021-01-15,97144,1594952.62,1061793.44,186481.22,2.450027,1.402269
1,yellow,2021-01-23,79320,1271373.58,854552.16,152780.70,2.564376,1.453984
2,yellow,2021-01-21,99038,1635703.00,1087443.64,193576.06,2.438613,1.387649
3,green,2021-01-13,1485,26461.29,21348.84,2087.05,3.304707,1.174411
4,green,2021-01-29,1577,27756.06,22531.73,1981.45,3.263862,1.175650
5,green,2021-01-30,1187,20547.37,17135.43,1490.08,3.503850,1.182814
6,yellow,2021-01-10,55872,1007166.84,699146.86,119676.42,3.241519,1.460875
7,yellow,2021-01-24,58064,999927.28,685996.78,118986.20,3.024194,1.455532
8,yellow,2021-01-12,91664,1490602.70,991577.54,173455.66,2.431922,1.385844
9,green,2021-01-08,1534,28090.32,22893.26,2141.58,162.618950,1.233377
10,green,2021-01-27,1490,27634.67,22465.39,1931.67,3.529282,1.184564
11,green,2021-01-31,913,15032.41,12193.13,1273.19,3.329463,1.185104
12,yellow,2021-01-26,87816,1386898.16,910739.00,165683.10,2.324859,1.380910
13,green,2021-01-11,1523,27225.82,21816.50,2247.31,3.277951,1.191070
14,green,2021-01-28,1609,27840.12,22292.55,2229.34,3.102859,1.185830
15,yellow,2021-01-08,92542,1507008.14,999118.90,175694.50,2.478124,1.403903
16,yellow,2021-01-31,58140,962211.62,652649.52,116794.80,6.699147,1.433127
17,green,2021-01-10,928,15069.04,12182.37,1305.33,3.093513,1.191810
18,green,2021-01-12,1504,27303.82,22047.60,2195.06,3.318118,1.203457
19,green,2021-01-24,879,14873.49,12050.59,1183.40,3.416985,1.187713
20,green,2021-01-26,1301,23618.36,19120.25,1708.89,3.492629,1.109147
21,yellow,2021-01-27,97044,1560382.24,1029208.40,184949.82,2.340444,1.364494
22,green,2021-01-17,863,14872.95,12053.64,1320.28,3.434797,1.200463
23,green,2021-01-22,1555,28237.62,23100.55,1893.36,3.430103,1.223794
24,green,2021-01-25,1327,23826.90,19370.41,1660.06,3.450452,1.174077
25,yellow,2021-01-11,85680,1405071.54,940379.14,160920.26,2.539556,1.391923
26,yellow,2021-01-28,104234,1676991.72,1103361.40,199861.56,2.334651,1.392041
27,yellow,2021-01-03,48840,969671.00,687033.42,113879.50,3.848812,1.445495
28,yellow,2021-01-07,92138,1528226.30,1021834.16,175237.60,2.559578,1.399813
29,green,2021-01-09,1278,22423.18,18557.46,1751.54,3.453341,1.207355
30,yellow,2021-01-22,100114,1627968.38,1073089.46,194757.32,2.398659,1.402501
31,yellow,2021-01-25,86790,1413649.04,941730.64,163828.92,2.479109,1.383869
32,yellow,2021-01-17,59794,1036149.36,713167.42,123316.90,3.032724,1.457370
33,yellow,2021-01-16,72562,1205659.86,819444.20,143538.56,2.757917,1.463686
34,green,2021-01-05,1441,25429.17,20778.16,1921.17,3.278251,1.176960
35,green,2021-01-14,1528,26980.95,21533.74,2248.41,3.296990,1.171466
36,green,2021-01-20,1382,24772.07,20027.88,1803.83,3.340485,1.154124
37,yellow,2021-01-09,74620,1252202.30,854052.96,148728.52,2.814297,1.457330
38,green,2021-01-03,786,13344.22,10830.49,1163.01,3.352532,1.206107
39,green,2021-01-07,1438,26217.07,21247.34,2008.59,3.379318,1.216273
40,yellow,2021-01-13,93852,1496869.12,986466.88,176249.94,2.354421,1.391446
41,green,2021-01-15,1525,27840.99,22556.72,2254.86,3.337666,1.180984
42,green,2021-01-21,1486,26197.82,21301.59,1873.69,3.284509,1.147376
43,green,2021-01-23,1311,22967.84,19020.10,1622.42,3.636026,1.255530
44,yellow,2021-01-29,101026,1631288.02,1073040.56,195992.96,2.347302,1.387960
45,yellow,2021-01-30,73676,1191046.82,803316.00,142955.84,2.594110,1.444867
46,yellow,2021-01-06,91000,1490748.12,994796.58,171470.90,2.513428,1.387890
47,yellow,2021-01-19,94176,1541758.44,1024583.96,181742.74,2.443917,1.395239
48,green,2021-01-02,1209,19876.27,16412.00,1598.10,3.241299,1.263854
49,green,2021-01-04,1431,24858.29,20140.05,1864.24,3.341551,1.194969
50,green,2021-01-18,998,18065.02,14748.45,1444.42,3.606643,1.128257
51,yellow,2021-01-02,64210,1180713.96,824708.86,138018.64,3.253532,1.492197
52,yellow,2021-01-04,81334,1428476.70,974412.86,161253.70,2.898823,1.400472
53,yellow,2021-01-18,68752,1156326.44,786621.10,136949.66,2.817172,1.399843
54,green,2021-01-06,1530,26829.53,21702.87,2017.75,3.399346,1.202614
55,green,2021-01-19,1445,25582.63,20560.90,1945.55,3.360893,1.177163
56,yellow,2021-01-05,85680,1428814.50,960771.44,162975.50,2.646228,1.403898
57,yellow,2021-01-14,97480,1597930.04,1063132.44,186471.22,2.484254,1.400616
58,yellow,2021-01-20,91336,1458985.70,957781.40,174974.36,2.408622,1.402777
59,green,2021-01-16,1250,21490.32,17654.32,1784.89,3.398920,1.239200

In [9]:
con.sql("SHOW ALL TABLES")

┌───────────────┬─────────┬──────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────┐
│   database    │ schema  │           name           │                                                                                                                                                                                                         column_names                                                                                                                                                                                                          │                                                                                                                                                          column_types                                                                                                                                                          │ temporary │
│    varchar    │ varchar │         varchar          │                                                                                                                                                                                                           varchar[]                                                                                                                                                                                                           │                                                                                                                                                           varchar[]                                                                                                                                                            │  boolean  │
├───────────────┼─────────┼──────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────────┤
│ taxi_rides_ny │ dev     │ dim_vendors              │ [vendor_id, vendor_name]                                                                                                                                                                                                                                                                                                                                                                                                      │ [INTEGER, VARCHAR]                                                                                                                                                                                                                                                                                                             │ false     │
│ taxi_rides_ny │ dev     │ dim_zones                │ [location_id, borough, zone, service_zone]                                                                                                                                                                                                                                                                                                                                                                                    │ [INTEGER, VARCHAR, VARCHAR, VARCHAR]                                                                                                                                                                                                                                                                                           │ false     │
│ taxi_rides_ny │ dev     │ fct_monthly_zone_revenue │ [pickup_zone, revenue_month, service_type, revenue_monthly_fare, revenue_monthly_extra, revenue_monthly_mta_tax, revenue_monthly_tip_amount, revenue_monthly_tolls_amount, revenue_monthly_ehail_fee, revenue_monthly_improvement_surcharge, revenue_monthly_total_amount, total_monthly_trips, avg_monthly_passenger_count, avg_monthly_trip_distance]                                                                       │ [VARCHAR, DATE, VARCHAR, 'DECIMAL(38,3)', 'DECIMAL(38,3)', 'DECIMAL(38,3)', 'DECIMAL(38,3)', 'DECIMAL(38,3)', 'DECIMAL(38,3)', 'DECIMAL(38,3)', 'DECIMAL(38,3)', BIGINT, DOUBLE, DOUBLE]                                                                                                                                       │ false     │
│ taxi_rides_ny │ dev     │ fct_trips                │ [trip_id, vendor_id, service_type, rate_code_id, pickup_location_id, pickup_borough, pickup_zone, dropoff_location_id, dropoff_borough, dropoff_zone, pickup_datetime, dropoff_datetime, store_and_fwd_flag, passenger_count, trip_distance, trip_type, trip_duration_minutes, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, payment_type_description] │ [VARCHAR, INTEGER, VARCHAR, INTEGER, INTEGER, VARCHAR, VARCHAR, INTEGER, VARCHAR, VARCHAR, TIMESTAMP, TIMESTAMP, VARCHAR, INTEGER, 'DECIMAL(18,3)', INTEGER, BIGINT, 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', INTEGER, VARCHAR] │ false     │
│ taxi_rides_ny │ dev     │ int_trips                │ [trip_id, vendor_id, service_type, rate_code_id, pickup_location_id, dropoff_location_id, pickup_datetime, dropoff_datetime, store_and_fwd_flag, passenger_count, trip_distance, trip_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, payment_type_description]                                                                                    │ [VARCHAR, INTEGER, VARCHAR, INTEGER, INTEGER, INTEGER, TIMESTAMP, TIMESTAMP, VARCHAR, INTEGER, 'DECIMAL(18,3)', INTEGER, 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', INTEGER, VARCHAR]                                             │ false     │
│ taxi_rides_ny │ dev     │ int_trips_unioned        │ [vendor_id, rate_code_id, pickup_location_id, dropoff_location_id, pickup_datetime, dropoff_datetime, store_and_fwd_flag, passenger_count, trip_distance, trip_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, service_type]                                                                                                                       │ [INTEGER, INTEGER, INTEGER, INTEGER, TIMESTAMP, TIMESTAMP, VARCHAR, INTEGER, 'DECIMAL(18,3)', INTEGER, 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', INTEGER, VARCHAR]                                                               │ false     │
│ taxi_rides_ny │ dev     │ payment_type_lookup      │ [payment_type, description]                                                                                                                                                                                                                                                                                                                                                                                                   │ [INTEGER, VARCHAR]                                                                                                                                                                                                                                                                                                             │ false     │
│ taxi_rides_ny │ dev     │ stg_green_tripdata       │ [vendor_id, rate_code_id, pickup_location_id, dropoff_location_id, pickup_datetime, dropoff_datetime, store_and_fwd_flag, passenger_count, trip_distance, trip_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type]                                                                                                                                     │ [INTEGER, INTEGER, INTEGER, INTEGER, TIMESTAMP, TIMESTAMP, VARCHAR, INTEGER, 'DECIMAL(18,3)', INTEGER, 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', INTEGER]                                                                        │ false     │
│ taxi_rides_ny │ dev     │ stg_yellow_tripdata      │ [vendor_id, rate_code_id, pickup_location_id, dropoff_location_id, pickup_datetime, dropoff_datetime, store_and_fwd_flag, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, payment_type]                                                                                                                                                           │ [INTEGER, INTEGER, INTEGER, INTEGER, TIMESTAMP, TIMESTAMP, VARCHAR, INTEGER, 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', INTEGER]                                                                                                  │ false     │
│ taxi_rides_ny │ dev     │ taxi_zone_lookup         │ [locationid, borough, zone, service_zone]                                                                                                                                                                                                                                                                                                                                                                                     │ [INTEGER, VARCHAR, VARCHAR, VARCHAR]                                                                                                                                                                                                                                                                                           │ false     │
│       ·       │  ·      │     ·                    │                     ·                                                                                                                                                                                                                                                                                                                                                                                                         │                  ·                                                                                                                                                                                                                                                                                                             │   ·       │
│       ·       │  ·      │     ·                    │                     ·                                                                                                                                                                                                                                                                                                                                                                                                         │                  ·                                                                                                                                                                                                                                                                                                             │   ·       │
│       ·       │  ·      │     ·                    │                     ·                                                                                                                                                                                                                                                                                                                                                                                                         │                  ·                                                                                                                                                                                                                                                                                                             │   ·       │
│ taxi_rides_ny │ prod    │ int_trips                │ [trip_id, vendor_id, service_type, rate_code_id, pickup_location_id, dropoff_location_id, pickup_datetime, dropoff_datetime, store_and_fwd_flag, passenger_count, trip_distance, trip_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, payment_type_description]                                                                                    │ [VARCHAR, INTEGER, VARCHAR, INTEGER, INTEGER, INTEGER, TIMESTAMP, TIMESTAMP, VARCHAR, INTEGER, 'DECIMAL(18,3)', INTEGER, 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', INTEGER, VARCHAR]                                             │ false     │
│ taxi_rides_ny │ prod    │ int_trips_unioned        │ [vendor_id, rate_code_id, pickup_location_id, dropoff_location_id, pickup_datetime, dropoff_datetime, store_and_fwd_flag, passenger_count, trip_distance, trip_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, service_type]                                                                                                                       │ [INTEGER, INTEGER, INTEGER, INTEGER, TIMESTAMP, TIMESTAMP, VARCHAR, INTEGER, 'DECIMAL(18,3)', INTEGER, 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', INTEGER, VARCHAR]                                                               │ false     │
│ taxi_rides_ny │ prod    │ payment_type_lookup      │ [payment_type, description]                                                                                                                                                                                                                                                                                                                                                                                                   │ [INTEGER, VARCHAR]                                                                                                                                                                                                                                                                                                             │ false     │
│ taxi_rides_ny │ prod    │ stg_fhv_tripdata         │ [dispatching_base_num, pickup_datetime, dropoff_datetime, pickup_location_id, dropoff_location_id, sr_flag, affiliated_base_number]                                                                                                                                                                                                                                                                                           │ [VARCHAR, TIMESTAMP, TIMESTAMP, INTEGER, INTEGER, VARCHAR, VARCHAR]                                                                                                                                                                                                                                                            │ false     │
│ taxi_rides_ny │ prod    │ stg_green_tripdata       │ [vendor_id, rate_code_id, pickup_location_id, dropoff_location_id, pickup_datetime, dropoff_datetime, store_and_fwd_flag, passenger_count, trip_distance, trip_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type]                                                                                                                                     │ [INTEGER, INTEGER, INTEGER, INTEGER, TIMESTAMP, TIMESTAMP, VARCHAR, INTEGER, 'DECIMAL(18,3)', INTEGER, 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', INTEGER]                                                                        │ false     │
│ taxi_rides_ny │ prod    │ stg_yellow_tripdata      │ [vendor_id, rate_code_id, pickup_location_id, dropoff_location_id, pickup_datetime, dropoff_datetime, store_and_fwd_flag, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, payment_type]                                                                                                                                                           │ [INTEGER, INTEGER, INTEGER, INTEGER, TIMESTAMP, TIMESTAMP, VARCHAR, INTEGER, 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', INTEGER]                                                                                                  │ false     │
│ taxi_rides_ny │ prod    │ taxi_zone_lookup         │ [locationid, borough, zone, service_zone]                                                                                                                                                                                                                                                                                                                                                                                     │ [INTEGER, VARCHAR, VARCHAR, VARCHAR]                                                                                                                                                                                                                                                                                           │ false     │

In [10]:
df = pd.DataFrame(con.sql("SHOW ALL TABLES").fetchall(), columns=["database", "schema", "name", "column_names", "column_types", "temporary"])
df

,database,schema,name,column_names,column_types,temporary
0,taxi_rides_ny,dev,dim_vendors,"[vendor_id, vendor_name]","[INTEGER, VARCHAR]",False
1,taxi_rides_ny,dev,dim_zones,"[location_id, borough, zone, service_zone]","[INTEGER, VARCHAR, VARCHAR, VARCHAR]",False
2,taxi_rides_ny,dev,fct_monthly_zone_revenue,"[pickup_zone, revenue_month, service_type, rev...","[VARCHAR, DATE, VARCHAR, DECIMAL(38,3), DECIMA...",False
3,taxi_rides_ny,dev,fct_trips,"[trip_id, vendor_id, service_type, rate_code_i...","[VARCHAR, INTEGER, VARCHAR, INTEGER, INTEGER, ...",False
4,taxi_rides_ny,dev,int_trips,"[trip_id, vendor_id, service_type, rate_code_i...","[VARCHAR, INTEGER, VARCHAR, INTEGER, INTEGER, ...",False
5,taxi_rides_ny,dev,int_trips_unioned,"[vendor_id, rate_code_id, pickup_location_id, ...","[INTEGER, INTEGER, INTEGER, INTEGER, TIMESTAMP...",False
6,taxi_rides_ny,dev,payment_type_lookup,"[payment_type, description]","[INTEGER, VARCHAR]",False
7,taxi_rides_ny,dev,stg_green_tripdata,"[vendor_id, rate_code_id, pickup_location_id, ...","[INTEGER, INTEGER, INTEGER, INTEGER, TIMESTAMP...",False
8,taxi_rides_ny,dev,stg_yellow_tripdata,"[vendor_id, rate_code_id, pickup_location_id, ...","[INTEGER, INTEGER, INTEGER, INTEGER, TIMESTAMP...",False
9,taxi_rides_ny,dev,taxi_zone_lookup,"[locationid, borough, zone, service_zone]","[INTEGER, VARCHAR, VARCHAR, VARCHAR]",False
10,taxi_rides_ny,ingestion,_dlt_loads,"[load_id, schema_name, status, inserted_at, sc...","[VARCHAR, VARCHAR, BIGINT, TIMESTAMP WITH TIME...",False
11,taxi_rides_ny,ingestion,_dlt_pipeline_state,"[version, engine_version, pipeline_name, state...","[BIGINT, BIGINT, VARCHAR, VARCHAR, TIMESTAMP W...",False
12,taxi_rides_ny,ingestion,_dlt_version,"[version, engine_version, inserted_at, schema_...","[BIGINT, BIGINT, TIMESTAMP WITH TIME ZONE, VAR...",False
13,taxi_rides_ny,ingestion,payment_lookup,"[payment_type_id, payment_type_name, _dlt_load...","[BIGINT, VARCHAR, VARCHAR, VARCHAR]",False
14,taxi_rides_ny,ingestion,trips,"[vendor_id, rate_code_id, pickup_location_id, ...","[DOUBLE, DOUBLE, BIGINT, BIGINT, VARCHAR, VARC...",False
15,taxi_rides_ny,prod,dim_vendors,"[vendor_id, vendor_name]","[INTEGER, VARCHAR]",False
16,taxi_rides_ny,prod,dim_zones,"[location_id, borough, zone, service_zone]","[INTEGER, VARCHAR, VARCHAR, VARCHAR]",False
17,taxi_rides_ny,prod,fct_monthly_zone_revenue,"[pickup_zone, revenue_month, service_type, rev...","[VARCHAR, DATE, VARCHAR, DECIMAL(38,3), DECIMA...",False
18,taxi_rides_ny,prod,fct_trips,"[trip_id, vendor_id, service_type, rate_code_i...","[VARCHAR, INTEGER, VARCHAR, INTEGER, INTEGER, ...",False
19,taxi_rides_ny,prod,fhv_tripdata,"[dispatching_base_num, pickup_datetime, dropOf...","[VARCHAR, TIMESTAMP, TIMESTAMP, BIGINT, BIGINT...",False
20,taxi_rides_ny,prod,green_tripdata,"[VendorID, lpep_pickup_datetime, lpep_dropoff_...","[BIGINT, TIMESTAMP, TIMESTAMP, VARCHAR, BIGINT...",False
21,taxi_rides_ny,prod,int_trips,"[trip_id, vendor_id, service_type, rate_code_i...","[VARCHAR, INTEGER, VARCHAR, INTEGER, INTEGER, ...",False
22,taxi_rides_ny,prod,int_trips_unioned,"[vendor_id, rate_code_id, pickup_location_id, ...","[INTEGER, INTEGER, INTEGER, INTEGER, TIMESTAMP...",False
23,taxi_rides_ny,prod,payment_type_lookup,"[payment_type, description]","[INTEGER, VARCHAR]",False
24,taxi_rides_ny,prod,stg_fhv_tripdata,"[dispatching_base_num, pickup_datetime, dropof...","[VARCHAR, TIMESTAMP, TIMESTAMP, INTEGER, INTEG...",False
25,taxi_rides_ny,prod,stg_green_tripdata,"[vendor_id, rate_code_id, pickup_location_id, ...","[INTEGER, INTEGER, INTEGER, INTEGER, TIMESTAMP...",False
26,taxi_rides_ny,prod,stg_yellow_tripdata,"[vendor_id, rate_code_id, pickup_location_id, ...","[INTEGER, INTEGER, INTEGER, INTEGER, TIMESTAMP...",False
27,taxi_rides_ny,prod,taxi_zone_lookup,"[locationid, borough, zone, service_zone]","[INTEGER, VARCHAR, VARCHAR, VARCHAR]",False
28,taxi_rides_ny,prod,yellow_tripdata,"[VendorID, tpep_pickup_datetime, tpep_dropoff_...","[BIGINT, TIMESTAMP, TIMESTAMP, BIGINT, DOUBLE,...",False
29,taxi_rides_ny,reports,trips_report,"[service_type, pickup_date, total_trips, total...","[VARCHAR, DATE, BIGINT, DOUBLE, DOUBLE, DOUBLE...",False
30,taxi_rides_ny,staging,trips,"[vendor_id, rate_code_id, pickup_location_id, ...","[DOUBLE, DOUBLE, BIGINT, BIGINT, VARCHAR, VARC...",False

In [18]:
con.close()