### Data Platforms with Bruin

In [26]:
import duckdb
import pandas as pd

**Note:** Jupyter kernel is running inside of the following directory, not the notebook's directory:

`zoomcamp/data-engineering-zoomcamp/04-analytics-engineering/taxi_rides_ny`

In [27]:
# Connect to the db.
con = duckdb.connect("taxi_rides_ny.duckdb")

In [28]:
#con.sql("DROP TABLE IF EXISTS staging.trips")
#con.sql("DROP TABLE IF EXISTS reports.trips_report")

In [29]:
# Check all schemata.
con.execute("SELECT * FROM information_schema.schemata").df()

,catalog_name,schema_name,schema_owner,default_character_set_catalog,default_character_set_schema,default_character_set_name,sql_path
0,system,information_schema,duckdb,None,None,None,None
1,system,main,duckdb,None,None,None,None
2,system,pg_catalog,duckdb,None,None,None,None
3,taxi_rides_ny,dev,duckdb,None,None,None,None
4,taxi_rides_ny,ingestion,duckdb,None,None,None,None
5,taxi_rides_ny,ingestion_staging,duckdb,None,None,None,None
6,taxi_rides_ny,main,duckdb,None,None,None,None
7,taxi_rides_ny,prod,duckdb,None,None,None,None
8,taxi_rides_ny,reports,duckdb,None,None,None,None
9,taxi_rides_ny,staging,duckdb,None,None,None,None
10,temp,main,duckdb,None,None,None,None

In [30]:
con.sql("SELECT * FROM staging.trips LIMIT 5").df()

,vendor_id,rate_code_id,pickup_location_id,dropoff_location_id,pickup_datetime,dropoff_datetime,store_and_fwd_flag,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,payment_type,payment_type_description,service_type,extracted_at
0,2.0,1.0,42,244,2021-01-02 00:14:34,2021-01-02 00:19:53,N,1.0,1.25,6.0,0.50,0.5,0.00,0.0,0.3,7.30,1.0,credit_card,green,2026-02-22 14:36:58.044440-05:00
1,2.0,1.0,75,220,2021-01-02 00:21:20,2021-01-02 00:52:01,N,1.0,9.11,31.0,0.50,0.5,0.00,0.0,0.3,32.30,1.0,credit_card,green,2026-02-22 14:36:58.044440-05:00
2,1.0,1.0,65,232,2021-01-02 00:09:02,2021-01-02 00:15:59,N,1.0,3.70,12.0,3.25,0.5,0.00,0.0,0.3,16.05,2.0,cash,green,2026-02-22 14:36:58.044440-05:00
3,1.0,1.0,75,20,2021-01-02 00:48:21,2021-01-02 01:06:31,N,2.0,9.40,26.0,0.50,0.5,0.02,0.0,0.3,27.32,1.0,credit_card,green,2026-02-22 14:36:58.044440-05:00
4,2.0,1.0,74,41,2021-01-02 00:56:04,2021-01-02 00:57:18,N,1.0,0.37,3.0,0.50,0.5,1.00,0.0,0.3,5.30,1.0,credit_card,green,2026-02-22 14:36:58.044440-05:00

In [31]:
con.sql("SELECT * FROM reports.trips_report").df()

,service_type,pickup_date,total_trips,total_amount,total_fare,total_tips,avg_trip_distance,avg_passenger_count
0,yellow,2021-01-29,50513,815644.01,536520.28,97996.48,2.347302,1.387960
1,yellow,2021-01-30,36838,595523.41,401658.00,71477.92,2.594110,1.444867
2,yellow,2021-01-27,48522,780191.12,514604.20,92474.91,2.340444,1.364494
3,green,2021-01-10,928,15069.04,12182.37,1305.33,3.093513,1.191810
4,green,2021-01-12,1504,27303.82,22047.60,2195.06,3.318118,1.203457
5,green,2021-01-24,879,14873.49,12050.59,1183.40,3.416985,1.187713
6,green,2021-01-26,1301,23618.36,19120.25,1708.89,3.492629,1.109147
7,yellow,2021-01-31,29070,481105.81,326324.76,58397.40,6.699147,1.433127
8,yellow,2021-01-08,46271,753504.07,499559.45,87847.25,2.478124,1.403903
9,yellow,2021-01-16,36281,602829.93,409722.10,71769.28,2.757917,1.463686
10,green,2021-01-05,1441,25429.17,20778.16,1921.17,3.278251,1.176960
11,green,2021-01-14,1528,26980.95,21533.74,2248.41,3.296990,1.171466
12,green,2021-01-20,1382,24772.07,20027.88,1803.83,3.340485,1.154124
13,green,2021-01-11,1523,27225.82,21816.50,2247.31,3.277951,1.191070
14,green,2021-01-28,1609,27840.12,22292.55,2229.34,3.102859,1.185830
15,yellow,2021-01-07,46069,764113.15,510917.08,87618.80,2.559578,1.399813
16,green,2021-01-09,1278,22423.18,18557.46,1751.54,3.453341,1.207355
17,yellow,2021-01-03,24420,484835.50,343516.71,56939.75,3.848812,1.445495
18,yellow,2021-01-28,52117,838495.86,551680.70,99930.78,2.334651,1.392041
19,yellow,2021-01-11,42840,702535.77,470189.57,80460.13,2.539556,1.391923
20,yellow,2021-01-06,45500,745374.06,497398.29,85735.45,2.513428,1.387890
21,yellow,2021-01-19,47088,770879.22,512291.98,90871.37,2.443917,1.395239
22,green,2021-01-02,1209,19876.27,16412.00,1598.10,3.241299,1.263854
23,green,2021-01-04,1431,24858.29,20140.05,1864.24,3.341551,1.194969
24,green,2021-01-18,998,18065.02,14748.45,1444.42,3.606643,1.128257
25,yellow,2021-01-18,34376,578163.22,393310.55,68474.83,2.817172,1.399843
26,green,2021-01-06,1530,26829.53,21702.87,2017.75,3.399346,1.202614
27,green,2021-01-19,1445,25582.63,20560.90,1945.55,3.360893,1.177163
28,yellow,2021-01-02,32105,590356.98,412354.43,69009.32,3.253532,1.492197
29,yellow,2021-01-04,40667,714238.35,487206.43,80626.85,2.898823,1.400472
30,green,2021-01-29,1577,27756.06,22531.73,1981.45,3.263862,1.175650
31,green,2021-01-30,1187,20547.37,17135.43,1490.08,3.503850,1.182814
32,yellow,2021-01-26,43908,693449.08,455369.50,82841.55,2.324859,1.380910
33,green,2021-01-08,1534,28090.32,22893.26,2141.58,162.618950,1.233377
34,green,2021-01-27,1490,27634.67,22465.39,1931.67,3.529282,1.184564
35,green,2021-01-31,913,15032.41,12193.13,1273.19,3.329463,1.185104
36,yellow,2021-01-12,45832,745301.35,495788.77,86727.83,2.431922,1.385844
37,yellow,2021-01-10,27936,503583.42,349573.43,59838.21,3.241519,1.460875
38,yellow,2021-01-24,29032,499963.64,342998.39,59493.10,3.024194,1.455532
39,yellow,2021-01-21,49519,817851.50,543721.82,96788.03,2.438613,1.387649
40,yellow,2021-01-15,48572,797476.31,530896.72,93240.61,2.450027,1.402269
41,green,2021-01-13,1485,26461.29,21348.84,2087.05,3.304707,1.174411
42,yellow,2021-01-23,39660,635686.79,427276.08,76390.35,2.564376,1.453984
43,green,2021-01-03,786,13344.22,10830.49,1163.01,3.352532,1.206107
44,green,2021-01-07,1438,26217.07,21247.34,2008.59,3.379318,1.216273
45,yellow,2021-01-09,37310,626101.15,427026.48,74364.26,2.814297,1.457330
46,green,2021-01-17,863,14872.95,12053.64,1320.28,3.434797,1.200463
47,green,2021-01-22,1555,28237.62,23100.55,1893.36,3.430103,1.223794
48,green,2021-01-25,1327,23826.90,19370.41,1660.06,3.450452,1.174077
49,green,2021-01-15,1525,27840.99,22556.72,2254.86,3.337666,1.180984
50,green,2021-01-21,1486,26197.82,21301.59,1873.69,3.284509,1.147376
51,green,2021-01-23,1311,22967.84,19020.10,1622.42,3.636026,1.255530
52,yellow,2021-01-13,46926,748434.56,493233.44,88124.97,2.354421,1.391446
53,yellow,2021-01-22,50057,813984.19,536544.73,97378.66,2.398659,1.402501
54,yellow,2021-01-25,43395,706824.52,470865.32,81914.46,2.479109,1.383869
55,yellow,2021-01-17,29897,518074.68,356583.71,61658.45,3.032724,1.457370
56,yellow,2021-01-05,42840,714407.25,480385.72,81487.75,2.646228,1.403898
57,yellow,2021-01-20,45668,729492.85,478890.70,87487.18,2.408622,1.402777
58,green,2021-01-16,1250,21490.32,17654.32,1784.89,3.398920,1.239200
59,yellow,2021-01-14,48740,798965.02,531566.22,93235.61,2.484254,1.400616

In [32]:
con.sql("SHOW ALL TABLES")

┌───────────────┬─────────┬──────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────┐
│   database    │ schema  │           name           │                                                                                                                                                                                                         column_names                                                                                                                                                                                                          │                                                                                                                                                          column_types                                                                                                                                                          │ temporary │
│    varchar    │ varchar │         varchar          │                                                                                                                                                                                                           varchar[]                                                                                                                                                                                                           │                                                                                                                                                           varchar[]                                                                                                                                                            │  boolean  │
├───────────────┼─────────┼──────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────────┤
│ taxi_rides_ny │ dev     │ dim_vendors              │ [vendor_id, vendor_name]                                                                                                                                                                                                                                                                                                                                                                                                      │ [INTEGER, VARCHAR]                                                                                                                                                                                                                                                                                                             │ false     │
│ taxi_rides_ny │ dev     │ dim_zones                │ [location_id, borough, zone, service_zone]                                                                                                                                                                                                                                                                                                                                                                                    │ [INTEGER, VARCHAR, VARCHAR, VARCHAR]                                                                                                                                                                                                                                                                                           │ false     │
│ taxi_rides_ny │ dev     │ fct_monthly_zone_revenue │ [pickup_zone, revenue_month, service_type, revenue_monthly_fare, revenue_monthly_extra, revenue_monthly_mta_tax, revenue_monthly_tip_amount, revenue_monthly_tolls_amount, revenue_monthly_ehail_fee, revenue_monthly_improvement_surcharge, revenue_monthly_total_amount, total_monthly_trips, avg_monthly_passenger_count, avg_monthly_trip_distance]                                                                       │ [VARCHAR, DATE, VARCHAR, 'DECIMAL(38,3)', 'DECIMAL(38,3)', 'DECIMAL(38,3)', 'DECIMAL(38,3)', 'DECIMAL(38,3)', 'DECIMAL(38,3)', 'DECIMAL(38,3)', 'DECIMAL(38,3)', BIGINT, DOUBLE, DOUBLE]                                                                                                                                       │ false     │
│ taxi_rides_ny │ dev     │ fct_trips                │ [trip_id, vendor_id, service_type, rate_code_id, pickup_location_id, pickup_borough, pickup_zone, dropoff_location_id, dropoff_borough, dropoff_zone, pickup_datetime, dropoff_datetime, store_and_fwd_flag, passenger_count, trip_distance, trip_type, trip_duration_minutes, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, payment_type_description] │ [VARCHAR, INTEGER, VARCHAR, INTEGER, INTEGER, VARCHAR, VARCHAR, INTEGER, VARCHAR, VARCHAR, TIMESTAMP, TIMESTAMP, VARCHAR, INTEGER, 'DECIMAL(18,3)', INTEGER, BIGINT, 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', INTEGER, VARCHAR] │ false     │
│ taxi_rides_ny │ dev     │ int_trips                │ [trip_id, vendor_id, service_type, rate_code_id, pickup_location_id, dropoff_location_id, pickup_datetime, dropoff_datetime, store_and_fwd_flag, passenger_count, trip_distance, trip_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, payment_type_description]                                                                                    │ [VARCHAR, INTEGER, VARCHAR, INTEGER, INTEGER, INTEGER, TIMESTAMP, TIMESTAMP, VARCHAR, INTEGER, 'DECIMAL(18,3)', INTEGER, 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', INTEGER, VARCHAR]                                             │ false     │
│ taxi_rides_ny │ dev     │ int_trips_unioned        │ [vendor_id, rate_code_id, pickup_location_id, dropoff_location_id, pickup_datetime, dropoff_datetime, store_and_fwd_flag, passenger_count, trip_distance, trip_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, service_type]                                                                                                                       │ [INTEGER, INTEGER, INTEGER, INTEGER, TIMESTAMP, TIMESTAMP, VARCHAR, INTEGER, 'DECIMAL(18,3)', INTEGER, 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', INTEGER, VARCHAR]                                                               │ false     │
│ taxi_rides_ny │ dev     │ payment_type_lookup      │ [payment_type, description]                                                                                                                                                                                                                                                                                                                                                                                                   │ [INTEGER, VARCHAR]                                                                                                                                                                                                                                                                                                             │ false     │
│ taxi_rides_ny │ dev     │ stg_green_tripdata       │ [vendor_id, rate_code_id, pickup_location_id, dropoff_location_id, pickup_datetime, dropoff_datetime, store_and_fwd_flag, passenger_count, trip_distance, trip_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type]                                                                                                                                     │ [INTEGER, INTEGER, INTEGER, INTEGER, TIMESTAMP, TIMESTAMP, VARCHAR, INTEGER, 'DECIMAL(18,3)', INTEGER, 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', INTEGER]                                                                        │ false     │
│ taxi_rides_ny │ dev     │ stg_yellow_tripdata      │ [vendor_id, rate_code_id, pickup_location_id, dropoff_location_id, pickup_datetime, dropoff_datetime, store_and_fwd_flag, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, payment_type]                                                                                                                                                           │ [INTEGER, INTEGER, INTEGER, INTEGER, TIMESTAMP, TIMESTAMP, VARCHAR, INTEGER, 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', INTEGER]                                                                                                  │ false     │
│ taxi_rides_ny │ dev     │ taxi_zone_lookup         │ [locationid, borough, zone, service_zone]                                                                                                                                                                                                                                                                                                                                                                                     │ [INTEGER, VARCHAR, VARCHAR, VARCHAR]                                                                                                                                                                                                                                                                                           │ false     │
│       ·       │  ·      │     ·                    │                     ·                                                                                                                                                                                                                                                                                                                                                                                                         │                  ·                                                                                                                                                                                                                                                                                                             │   ·       │
│       ·       │  ·      │     ·                    │                     ·                                                                                                                                                                                                                                                                                                                                                                                                         │                  ·                                                                                                                                                                                                                                                                                                             │   ·       │
│       ·       │  ·      │     ·                    │                     ·                                                                                                                                                                                                                                                                                                                                                                                                         │                  ·                                                                                                                                                                                                                                                                                                             │   ·       │
│ taxi_rides_ny │ prod    │ int_trips                │ [trip_id, vendor_id, service_type, rate_code_id, pickup_location_id, dropoff_location_id, pickup_datetime, dropoff_datetime, store_and_fwd_flag, passenger_count, trip_distance, trip_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, payment_type_description]                                                                                    │ [VARCHAR, INTEGER, VARCHAR, INTEGER, INTEGER, INTEGER, TIMESTAMP, TIMESTAMP, VARCHAR, INTEGER, 'DECIMAL(18,3)', INTEGER, 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', INTEGER, VARCHAR]                                             │ false     │
│ taxi_rides_ny │ prod    │ int_trips_unioned        │ [vendor_id, rate_code_id, pickup_location_id, dropoff_location_id, pickup_datetime, dropoff_datetime, store_and_fwd_flag, passenger_count, trip_distance, trip_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, service_type]                                                                                                                       │ [INTEGER, INTEGER, INTEGER, INTEGER, TIMESTAMP, TIMESTAMP, VARCHAR, INTEGER, 'DECIMAL(18,3)', INTEGER, 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', INTEGER, VARCHAR]                                                               │ false     │
│ taxi_rides_ny │ prod    │ payment_type_lookup      │ [payment_type, description]                                                                                                                                                                                                                                                                                                                                                                                                   │ [INTEGER, VARCHAR]                                                                                                                                                                                                                                                                                                             │ false     │
│ taxi_rides_ny │ prod    │ stg_fhv_tripdata         │ [dispatching_base_num, pickup_datetime, dropoff_datetime, pickup_location_id, dropoff_location_id, sr_flag, affiliated_base_number]                                                                                                                                                                                                                                                                                           │ [VARCHAR, TIMESTAMP, TIMESTAMP, INTEGER, INTEGER, VARCHAR, VARCHAR]                                                                                                                                                                                                                                                            │ false     │
│ taxi_rides_ny │ prod    │ stg_green_tripdata       │ [vendor_id, rate_code_id, pickup_location_id, dropoff_location_id, pickup_datetime, dropoff_datetime, store_and_fwd_flag, passenger_count, trip_distance, trip_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type]                                                                                                                                     │ [INTEGER, INTEGER, INTEGER, INTEGER, TIMESTAMP, TIMESTAMP, VARCHAR, INTEGER, 'DECIMAL(18,3)', INTEGER, 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', INTEGER]                                                                        │ false     │
│ taxi_rides_ny │ prod    │ stg_yellow_tripdata      │ [vendor_id, rate_code_id, pickup_location_id, dropoff_location_id, pickup_datetime, dropoff_datetime, store_and_fwd_flag, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, payment_type]                                                                                                                                                           │ [INTEGER, INTEGER, INTEGER, INTEGER, TIMESTAMP, TIMESTAMP, VARCHAR, INTEGER, 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', 'DECIMAL(18,3)', INTEGER]                                                                                                  │ false     │
│ taxi_rides_ny │ prod    │ taxi_zone_lookup         │ [locationid, borough, zone, service_zone]                                                                                                                                                                                                                                                                                                                                                                                     │ [INTEGER, VARCHAR, VARCHAR, VARCHAR]                                                                                                                                                                                                                                                                                           │ false     │

In [33]:
df = pd.DataFrame(con.sql("SHOW ALL TABLES").fetchall(), columns=["database", "schema", "name", "column_names", "column_types", "temporary"])
df

,database,schema,name,column_names,column_types,temporary
0,taxi_rides_ny,dev,dim_vendors,"[vendor_id, vendor_name]","[INTEGER, VARCHAR]",False
1,taxi_rides_ny,dev,dim_zones,"[location_id, borough, zone, service_zone]","[INTEGER, VARCHAR, VARCHAR, VARCHAR]",False
2,taxi_rides_ny,dev,fct_monthly_zone_revenue,"[pickup_zone, revenue_month, service_type, rev...","[VARCHAR, DATE, VARCHAR, DECIMAL(38,3), DECIMA...",False
3,taxi_rides_ny,dev,fct_trips,"[trip_id, vendor_id, service_type, rate_code_i...","[VARCHAR, INTEGER, VARCHAR, INTEGER, INTEGER, ...",False
4,taxi_rides_ny,dev,int_trips,"[trip_id, vendor_id, service_type, rate_code_i...","[VARCHAR, INTEGER, VARCHAR, INTEGER, INTEGER, ...",False
5,taxi_rides_ny,dev,int_trips_unioned,"[vendor_id, rate_code_id, pickup_location_id, ...","[INTEGER, INTEGER, INTEGER, INTEGER, TIMESTAMP...",False
6,taxi_rides_ny,dev,payment_type_lookup,"[payment_type, description]","[INTEGER, VARCHAR]",False
7,taxi_rides_ny,dev,stg_green_tripdata,"[vendor_id, rate_code_id, pickup_location_id, ...","[INTEGER, INTEGER, INTEGER, INTEGER, TIMESTAMP...",False
8,taxi_rides_ny,dev,stg_yellow_tripdata,"[vendor_id, rate_code_id, pickup_location_id, ...","[INTEGER, INTEGER, INTEGER, INTEGER, TIMESTAMP...",False
9,taxi_rides_ny,dev,taxi_zone_lookup,"[locationid, borough, zone, service_zone]","[INTEGER, VARCHAR, VARCHAR, VARCHAR]",False
10,taxi_rides_ny,ingestion,_dlt_loads,"[load_id, schema_name, status, inserted_at, sc...","[VARCHAR, VARCHAR, BIGINT, TIMESTAMP WITH TIME...",False
11,taxi_rides_ny,ingestion,_dlt_pipeline_state,"[version, engine_version, pipeline_name, state...","[BIGINT, BIGINT, VARCHAR, VARCHAR, TIMESTAMP W...",False
12,taxi_rides_ny,ingestion,_dlt_version,"[version, engine_version, inserted_at, schema_...","[BIGINT, BIGINT, TIMESTAMP WITH TIME ZONE, VAR...",False
13,taxi_rides_ny,ingestion,payment_lookup,"[payment_type_id, payment_type_name, _dlt_load...","[BIGINT, VARCHAR, VARCHAR, VARCHAR]",False
14,taxi_rides_ny,ingestion,trips,"[vendor_id, rate_code_id, pickup_location_id, ...","[DOUBLE, DOUBLE, BIGINT, BIGINT, VARCHAR, VARC...",False
15,taxi_rides_ny,ingestion_staging,_dlt_version,"[version, engine_version, inserted_at, schema_...","[BIGINT, BIGINT, TIMESTAMP WITH TIME ZONE, VAR...",False
16,taxi_rides_ny,prod,dim_vendors,"[vendor_id, vendor_name]","[INTEGER, VARCHAR]",False
17,taxi_rides_ny,prod,dim_zones,"[location_id, borough, zone, service_zone]","[INTEGER, VARCHAR, VARCHAR, VARCHAR]",False
18,taxi_rides_ny,prod,fct_monthly_zone_revenue,"[pickup_zone, revenue_month, service_type, rev...","[VARCHAR, DATE, VARCHAR, DECIMAL(38,3), DECIMA...",False
19,taxi_rides_ny,prod,fct_trips,"[trip_id, vendor_id, service_type, rate_code_i...","[VARCHAR, INTEGER, VARCHAR, INTEGER, INTEGER, ...",False
20,taxi_rides_ny,prod,fhv_tripdata,"[dispatching_base_num, pickup_datetime, dropOf...","[VARCHAR, TIMESTAMP, TIMESTAMP, BIGINT, BIGINT...",False
21,taxi_rides_ny,prod,green_tripdata,"[VendorID, lpep_pickup_datetime, lpep_dropoff_...","[BIGINT, TIMESTAMP, TIMESTAMP, VARCHAR, BIGINT...",False
22,taxi_rides_ny,prod,int_trips,"[trip_id, vendor_id, service_type, rate_code_i...","[VARCHAR, INTEGER, VARCHAR, INTEGER, INTEGER, ...",False
23,taxi_rides_ny,prod,int_trips_unioned,"[vendor_id, rate_code_id, pickup_location_id, ...","[INTEGER, INTEGER, INTEGER, INTEGER, TIMESTAMP...",False
24,taxi_rides_ny,prod,payment_type_lookup,"[payment_type, description]","[INTEGER, VARCHAR]",False
25,taxi_rides_ny,prod,stg_fhv_tripdata,"[dispatching_base_num, pickup_datetime, dropof...","[VARCHAR, TIMESTAMP, TIMESTAMP, INTEGER, INTEG...",False
26,taxi_rides_ny,prod,stg_green_tripdata,"[vendor_id, rate_code_id, pickup_location_id, ...","[INTEGER, INTEGER, INTEGER, INTEGER, TIMESTAMP...",False
27,taxi_rides_ny,prod,stg_yellow_tripdata,"[vendor_id, rate_code_id, pickup_location_id, ...","[INTEGER, INTEGER, INTEGER, INTEGER, TIMESTAMP...",False
28,taxi_rides_ny,prod,taxi_zone_lookup,"[locationid, borough, zone, service_zone]","[INTEGER, VARCHAR, VARCHAR, VARCHAR]",False
29,taxi_rides_ny,prod,yellow_tripdata,"[VendorID, tpep_pickup_datetime, tpep_dropoff_...","[BIGINT, TIMESTAMP, TIMESTAMP, BIGINT, DOUBLE,...",False
30,taxi_rides_ny,reports,trips_report,"[service_type, pickup_date, total_trips, total...","[VARCHAR, DATE, BIGINT, DOUBLE, DOUBLE, DOUBLE...",False
31,taxi_rides_ny,staging,trips,"[vendor_id, rate_code_id, pickup_location_id, ...","[DOUBLE, DOUBLE, BIGINT, BIGINT, VARCHAR, VARC...",False

In [34]:
# con.close()